export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const RETRIEVE_SUCCESS = 'RETRIEVE_SUCCESS';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

export const SAVE_CLINICAL_STORY_START = 'SAVE_CLINICAL_STORY_START';
export const SAVE_CLINICAL_STORY_SUCCESS = 'SAVE_CLINICAL_STORY_SUCCESS';
export const SAVE_CLINICAL_STORY_FAIL = 'SAVE_CLINICAL_STORY_FAIL';

export const FETCH_CLINICAL_STORIES_START = 'FETCH_CLINICAL_STORIES_START';
export const FETCH_CLINICAL_STORIES_SUCCESS = 'FETCH_CLINICAL_STORIES_SUCCESS';
export const FETCH_CLINICAL_STORIES_FAIL = 'FETCH_CLINICAL_STORIES_FAIL';

export const REGISTER_START = 'REGISTER_START';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const INIT_FORM_DATA_START = 'INIT_FORM_DATA_START';
export const INIT_FORM_DATA_SUCCESS = 'INIT_FORM_DATA_SUCCESS';
export const INIT_FORM_DATA_FAIL = 'INIT_FORM_DATA_FAIL';
export const FETCH_STATES_SUCCESS = 'FETCH_STATES_SUCCESS';
export const FETCH_MUNICIPALITIES_SUCCESS = 'FETCH_MUNICIPALITIES_SUCCESS';

